#### 3. Perform the following operations on an array of mobile phones prices 6999, 7500,
11999, 27899, 14999, 9999.
a. Create a 1d-array of mobile phones prices
b. Convert this array to float type
c. Append a new mobile having price of 13999 Rs. to this array
d. Reverse this array of mobile phones prices
e. Apply GST of 18% on mobile phones prices and update this array.
f. Sort the array in descending order of price
g. What is the average mobile phone price
h. What is the difference b/w maximum and minimum price

In [1]:
## a. Create a 1d-array of mobile phones prices

In [2]:
import numpy as np

In [3]:
price=np.array([6999,7500,11999,27899,14999,9999])
price

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [4]:
###b. Convert this array to float type

In [5]:
price=price.astype(float)
print(price)

[ 6999.  7500. 11999. 27899. 14999.  9999.]


In [6]:
## c. Append a new mobile having price of 13999 Rs. to this array

In [7]:
price=np.append(price,13999)
print(price)

[ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [9]:
##d. Reverse this array of mobile phones prices

In [8]:
price=price[::-1]
print(price)

[13999.  9999. 14999. 27899. 11999.  7500.  6999.]


In [10]:
##e. Apply GST of 18% on mobile phones prices and update this array.

In [12]:
price=price*1.18
price

array([19492.2076, 13922.6076, 20884.6076, 38846.5676, 16707.4076,
       10443.    ,  9745.4076])

In [13]:
##f. Sort the array in descending order of price

In [14]:
price=np.sort(price)[::-1]
price

array([38846.5676, 20884.6076, 19492.2076, 16707.4076, 13922.6076,
       10443.    ,  9745.4076])

In [15]:
##g.Average mobile price

In [17]:
average=np.mean(price)
print("Average Price:",average)

Average Price: 18577.4008


In [18]:
##h. What is the difference b/w maximum and minimum price

In [19]:
difference=np.max(price)-np.min(price)
print("Difference:",difference)

Difference: 29101.159999999996
