In [1]:
##1. Create a NumPy array containing integers from 0 to 9.

In [2]:
import numpy as np

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
##2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [5]:
import numpy as np

In [11]:
list1=[10,20,30,40,50]
arr=np.array(list1)
arr

array([10, 20, 30, 40, 50])

In [12]:
import numpy as np

In [13]:
arr=np.arange(9).reshape(3,3)

In [14]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
##4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between
##1 and 100, and print the shape and size.

In [17]:
import numpy as np

In [18]:
arr=np.random.randint(1,101,(5,4))
arr
print("Shape:",arr.shape)
print("Size:",arr.size)

Shape: (5, 4)
Size: 20


In [20]:
##5.5. Create a 3x3 array of integers and access:
#a. The second element of the first row.
#b. The third column of the 2nd row.
#c. A subarray with the first two rows and last two columns.

In [21]:
import numpy as np

In [22]:
arr=np.array([[1,2,3],
              [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#a.
print(arr[0,1])


2


In [26]:
#b.
print(arr[1,2])

6


In [27]:
#c.
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [28]:
##6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [29]:
import numpy as np

In [30]:
arr=np.arange(12)

In [31]:
print("1D Array:")
print(arr)

1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
arr2=arr.reshape(3,4)

In [33]:
print("3*4 Array:")
print(arr2)

3*4 Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
##7. Reshape a 3x3 matrix into a 1D array.

In [36]:
import numpy as np

In [37]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr1=arr.reshape(9)

In [38]:
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [39]:
##8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
#subtraction, multiplication, and division on them.

In [40]:
import numpy as np

In [42]:
arr1=np.array([[10,20,30],
               [40,50,60]])
arr2=np.array([[2,4,5],
               [5,10,10]])
print("Addition:")
print(arr1+arr2)

print("Subtraction:")
print(arr1-arr2)

print("Multiplications:")
print(arr1*arr2)

print("Division:")
print(arr1/arr2)

Addition:
[[12 24 35]
 [45 60 70]]
Subtraction:
[[ 8 16 25]
 [35 40 50]]
Multiplications:
[[ 20  80 150]
 [200 500 600]]
Division:
[[5. 5. 6.]
 [8. 5. 6.]]


In [43]:
##9.Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a
#given array.

In [44]:
import numpy as np

In [45]:
arr=np.array([10,20,30,40,50])

print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))

Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951


In [46]:
##10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
#the @ operator.

In [47]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])
result=np.dot(A,B)
result

array([[19, 22],
       [43, 50]])

In [48]:
##11. Find the transpose of matrix A and matrix B.

In [49]:
import numpy as np

In [51]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])
print("Transpose of A:")
print(A.T)
print("Transpose of B:")
print(B.T)

Transpose of A:
[[1 3]
 [2 4]]
Transpose of B:
[[5 7]
 [6 8]]


In [53]:
##12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
#Explain how broadcasting works in this operation.

In [54]:
import numpy as np

In [58]:
arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr1D=np.array([10,20,30])
result=arr2D+arr1D
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [59]:
#13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the
#entire array.

In [60]:
import numpy as np

In [61]:
arr=np.random.randint(1,101,(4,4))
print(arr)
print("Maximum:",np.max(arr))
print("Minimum:",np.min(arr))
print("Mean:",np.mean(arr))

[[ 57  48  22  31]
 [100  79  44  46]
 [ 14   1  94  81]
 [ 38  91  90  21]]
Maximum: 100
Minimum: 1
Mean: 53.5625


In [62]:
##14.Row-wise and Column-wise sums

In [63]:
import numpy as np

In [64]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Row-wise sum:")
print(np.sum(arr,axis=1))

print("Column-wise sum:")
print(np.sum(arr,axis=0))

Row-wise sum:
[ 6 15 24]
Column-wise sum:
[12 15 18]


In [65]:
##15.15. Generate an array of 10 random integers between 1 and 50.

In [66]:
import numpy as np

In [67]:
arr=np.random.randint(1,51,10)
print(arr)

[11 44 31 37 30 13 41  9 19 35]


In [68]:
##16. Generate a 5x5 matrix of random floats between 0 and 1.

In [69]:
import numpy as np

In [72]:
arr=np.random.rand(5,5)
arr

array([[0.55630993, 0.4978717 , 0.07344656, 0.34632058, 0.43496748],
       [0.79650753, 0.31771075, 0.33730347, 0.68467111, 0.75709171],
       [0.07525664, 0.85778343, 0.72823431, 0.79925337, 0.72052166],
       [0.77825667, 0.15494608, 0.79973631, 0.50802026, 0.87099054],
       [0.44326189, 0.17116858, 0.79170336, 0.28556207, 0.71454183]])